name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: List Repo Files
          run: ls -la

        - name: Executing shell script
          run: |
            chmod +x .github/workflows/ascii-script.sh
            ./.github/workflows/ascii-script.sh