name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Install cowsay package
          run: sudo apt-get install -y cowsay

        - name: Execute cowsay command
          run: cowsay -f elephant "Hello elephant from GitHub Actions!" >> elephant.txt

        - name: Test File Exists
          run: grep -i "elephant" elephant.txt

        - name: Read File
          run: cat elephant.txt

        - name: List Repo Files
          run: ls -ltra