name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Install cowsay package
          run: sudo apt-get install -y cowsay

        - name: Execute cowsay command
          run: cowsay -f dragon "Hello from GitHub Actions!" >> dragon.txt

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

        - name: Read File
          run: cat dragon.txt

        - name: List Repo Files
          run: ls -ltra