name: My First Wokflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: List and Read File
          run: |
            echo "My First Githiub Actions Job"
            ls -ltra
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Hello from GitHub Actions!" >> dragon.txt      

        # - name: List Files
        #   run: ls

        # - name: Read File
        #   run: cat README.md