name: Matrix Configuration

on:
    workflow_dispatch:

jobs:       
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04] 
                images: [hello-world, alpine, nginx]    
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info

        - name: Run Images on ${{ matrix.os }}         
          run: docker run ${{ matrix.images }}










