name: Matrix Configuration

on:
    workflow_dispatch:

jobs:       
    deploy:
        strategy:
            max-parallel: 3
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, ubuntu-24.04] 
                images: [hello-world, alpine, nginx]    
                exclude:
                    - os: ubuntu-24.04
                      images: nginx
                    - os: ubuntu-22.04
                      images: alpine
                    - os: ubuntu-latest
                      images: hello-world
        runs-on: ${{ matrix.os }}
        steps:
        - name: Echo Docker Details
          run: docker info

        - name: Run Images on ${{ matrix.os }}         
          run: docker run ${{ matrix.images }}










