name: Generate ASCII Artwork - multiple jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout Repository
        #   uses: actions/checkout@v4

        - name: install cowsay Package
          run: sudo apt-get install -y cowsay
    
        - name: Execute Cowsay Command
          run: cowsay -f turkey "Hello turkey from GitHub Actions!" >> turkey.txt

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: turkey-artifact
            path: turkey.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout Repository
        #   uses: actions/checkout@v4

        - name: download artifact
          uses: actions/download-artifact@v4
          with:
            name: turkey-artifact
    
        - name: Test File Exists
          run: grep -i "turkey" turkey.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout Repository
        #   uses: actions/checkout@v4
        
        - name: download artifact
          uses: actions/download-artifact@v4
          with:
            name: turkey-artifact
            
        - name: Read File
          run: cat turkey.txt

        - name: Deploy File
          run: echo Deploying ... .. .
          
    
   

 
