name: Exploring Variables and Secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: zakirhush
    DOCKER_IMAGE_NAME: github-actions-nginx
    DOCKER_PASSWORD: s3cUrePassw0rd

jobs:
    # docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Build
    #       run: docker build -t docker.io/dockerUsername/imageName:latest
          
    #     - name: Docker Login
    #       run: docker login --username=dockerUsername --password=s3cUrePassw0rd

    #     - name: Docker Publish
    #       run: docker push docker.io/dockerUsername/imageName:latest

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Run
    #       run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

# ============ declared environment at steps level ==============

    # docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Build
    #       env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: zakirhush
    #         DOCKER_IMAGE_NAME: github-actions-nginx
    #       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
          
    #     - name: Docker Login
    #       env:
    #         DOCKER_USERNAME: zakirhush
    #         DOCKER_PASSWORD: S3cUrePassw0rd
    #       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    #     - name: Docker Publish
    #       env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: zakirhush
    #         DOCKER_IMAGE_NAME: github-actions-nginx
    #       run: echo docket push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Run
    #       env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: zakirhush
    #         DOCKER_IMAGE_NAME: github-actions-nginx
    #       run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

# =================== variables decelared in job level =========================

    # docker:
    #     env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: zakirhush
    #         DOCKER_IMAGE_NAME: github-actions-nginx
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Build
    #       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest  

    #     - name: Docker Login
    #       env:
    #         DOCKER_PASSWORD: s3cUrePassw0rd
    #       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    #     - name: Docker Publish
    #       run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

    # deploy:
    #     needs: docker
    #     env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: zakirhush
    #         DOCKER_IMAGE_NAME: github-actions-nginx 
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Run
    #       run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest     

# ================== variables decelared in workflow level =========================
        
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest  

        - name: Docker Login            
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest 








